### ISSUE TITLE
UI Enhancement

### ISSUE THREAD

**Issue by aryangusain** [Gaurav-meena95/Stone_Paper_Scissors#2]
Hey @Gaurav-meena95, really good project but the current UI is laid out in a way that the usability is not effective, like If I choose stone, I have to scroll down to see the result.
I can improve the UI. This is my [portfolio](https://aryanx.dev) btw

If you want me to work on this, just assign me this issue and I'll start right away.
I'll complete the work within an hour.

**Comment by Gaurav-meena95** [comment]
ohh! yah i corrected it

**Comment by aryangusain** [comment]
no, it should be hacktoberfest, you've written hactoberfest, you missed a k
